---
# version of node to install, defaults to 'latest'
node_version: 'node'

# version of nvm to install, defaults to 'latest'
# when using latest, the role will pick the latest version from github
node_nvm_version: 'latest'

# Install path for nvm (defaults to $HOME/.nvm)
node_nvm_install_path: "{{ ansible_facts['env']['HOME'] }}/.nvm"
